### ISSUE TITLE
Abstraction of final return in invoke()

### ISSUE THREAD

**Issue by Tom-OriginStorage** [polyphene/fvm-rs-sdk#1]
https://github.com/polyphene/fvm-rs-sdk/blob/19f075251dd5eec73434b6d66fd2f414c8fd9343/examples/sdk-example-actor/src/lib.rs#L61

I believe line 59 to 68 can be abstracted away into a macro or something? 
It will always be the same for all actors I believe.

**Comment by Tom-OriginStorage** [comment]
https://github.com/polyphene/fvm-rs-sdk/blob/19f075251dd5eec73434b6d66fd2f414c8fd9343/examples/sdk-example-actor/src/lib.rs#L16

This line could also be possibly be abstracted into the same macro

**Comment by tchataigner** [comment]
Hey Tom, thanks for the feedback!

It is planned that in the next milestone to be delivered on the 08th of August a procedural macro will be available to generate glue code for the `invoke()` part of the contract.

More info can be found on the dedicated grant proposal https://github.com/filecoin-project/devgrants/issues/562

**Comment by Tom-OriginStorage** [comment]
Sorry my bad! Looks like I got impatient. Forgot about the grant milestone. ><

Just wondering will there be a proc macro to support automatic method number generation? And also will there be plans to support what was discussed in https://github.com/filecoin-project/FIPs/discussions/382?

**Comment by tchataigner** [comment]
No trouble! I should have shared the grant specs along with the repo link :) 

> Just wondering will there be a proc macro to support automatic method number generation?

There won't be an automatic generation, methods to be available as entry points will have to be tagged with `#[fvm_export(binding=<method-number>]` to be effectively taken into account.

> And also will there be plans to support what was discussed in https://github.com/filecoin-project/FIPs/discussions/382?

This dispatch method was not planned in our grant proposal. Also I after going through the discussion quite quickly I feel like the proposal specs is not stable yet so it should be considered for future release. Would you agree with that statement?

**Comment by Tom-OriginStorage** [comment]
> No trouble! I should have shared the grant specs along with the repo link :)

🤗
> There won't be an automatic generation, methods to be available as entry points will have to be tagged with #[fvm_export(binding=<method-number>] to be effectively taken into account.

Ah I see. Got it! 👍
> Would you agree with that statement?

Agree, and there are pro & cons to various specs. While I do have my own opinions, we will definitely follow the final specs that is actually implemented/decided even if it means restructuring the entire codebase. If you have any inclination to any type of specs, please do share your opinions too in https://github.com/filecoin-project/FIPs/discussions/382!

**Comment by tchataigner** [comment]
Hey @Tom-OriginStorage ! We release our 1.0 with new procedural macros, `#[fvm_actor]` and `#[fvm_export]`, you can find more on the [documentation site](https://polyphene.github.io/fvm-rs-sdk-docs/).

As this is now available I will close this issue. Please feel free to open a new one if you use them and you have some comments!
