### ISSUE TITLE
Abstraction of partial return in method return

### ISSUE THREAD

**Issue by Tom-OriginStorage** [polyphene/fvm-rs-sdk#2]
https://github.com/polyphene/fvm-rs-sdk/blob/19f075251dd5eec73434b6d66fd2f414c8fd9343/examples/sdk-example-actor/src/lib.rs#L42

From line 42 to 51, what we are always doing is take a value, `to_vec()` it and check if its serializable, we can abstract this to either a macro or function for this

**Comment by tchataigner** [comment]
As per the other comment I left, https://github.com/polyphene/fvm-rs-sdk/issues/1#issuecomment-1198407727, I think this should be solved once the `#[fvm_actor]` is available. Would be glad for you to take a look once it is available!

**Comment by tchataigner** [comment]
As per this coment on the other issue, https://github.com/polyphene/fvm-rs-sdk/issues/1#issuecomment-1214754948, I am closing this one!
