### ISSUE TITLE
Reference and credit `fil_fungible_token`

### ISSUE THREAD

**Issue by raulk** [polyphene/fvm-rs-sdk#3]
- (from where it was originally taken) 
- Does it have an explicit license? If not, we should ask the team to add it to avoid licensing surprises.

**Comment by tchataigner** [comment]
You're right, as you said on slack it is good OSS practices. The code was copied and altered from [Helix repository](https://github.com/helix-onchain/filecoin).

Licensing is alright, we will add a reference to their work in the README of the example !

**Comment by tchataigner** [comment]
The Helix team work has been [mentioned and linked to](https://github.com/polyphene/fvm-rs-sdk/blob/main/examples/fil_fungible_token/README.md) in the README of the example in the 1.0.1 release.

Closing the issue !
