### ISSUE TITLE
Rename `fvm_export(binding = ...)` to `fvm_export(method_num = ...)`

### ISSUE THREAD

**Issue by raulk** [polyphene/fvm-rs-sdk#4]
This is more explicit and self-descriptive, by expressing the binding style in the attribute declaration.

**Comment by tchataigner** [comment]
So we should just remove the binding style from `#[fvm_actor]` and only integrate it in `#[fvm_export]` ?

I guess it allows for a more flexible actor entry point declaration by mixing binding style on one entry point. Wouldn't that be weird to have multiple binding style for methods in one actor though ?

**Comment by tchataigner** [comment]
As it can be seen in [the tests file for the SDK](https://github.com/polyphene/fvm-rs-sdk/blob/main/macro/tests/proc-macro-tests/fvm_actor_pass.rs#L11-L24) this revamp was implemented in the release 1.0.1. Closing the issue :)
