### ISSUE TITLE
Do we still have the ability to have a custom invoke method?

### ISSUE THREAD

**Issue by raulk** [polyphene/fvm-rs-sdk#5]
If not, this is quite prohibitive. The invoke method isn't merely about dispatch and serde -- users may want to include top level ACLs/permission checks, or other functionality that applies to every call.

**Comment by tchataigner** [comment]
If people do not use `#[fvm_actor]` and `#[fvm_export]` and solely rely on `#[fvm_state]` for example they will be able to design and develop their own `invoke()` function 👍

**Comment by tchataigner** [comment]
I think the answer for this issue have been provided, closing it !
