### ISSUE TITLE
Making the format of the `#[fvm_payload]` attribute explicit

### ISSUE THREAD

**Issue by raulk** [polyphene/fvm-rs-sdk#6]
I know we're using CBOR under the hood, and it'll likely be that way for the near future. However, it's natural for users to wonder: "how does this payload serialise?". If we make the serialization strategy explicit, it'll kill two birds with one stone (information, and extension point for the future): `#[fvm_payload(codec = DagCbor)]`.

**Comment by tchataigner** [comment]
It makes sense for information, and extension point for the future as you say. Taking the feedback into account, thanks !

**Comment by tchataigner** [comment]
After the release 1.0.1, the `#[fvm_payload]` procedural macro now has a `codec` attribute which unique and default value is `dag-cbor`. Closing the issue 👍
